name: rebuild-website
on:
  push:
    branches:
      - main
    paths: # only rebuild when related files change
      - "**.md"
      - "**.yml"
      - "**.json"
      - "**.tsp"  

jobs:
  rebuild-website:
    name: Trigger deploy hooks
    runs-on: ubuntu-latest
    if: github.repository == 'blue-build/modules'
    steps: 
      - run: echo "schemas:" && curl -X POST -d {} ${{ secrets.SCHEMAS_DEPLOY_HOOK }}
